# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build AAB and upload to Internal Track"
  lane :build_and_upload_internal do
    skip_docs
    gradle(
    task: "bundle",
    build_type: 'release'
    )
    upload_to_play_store(
      track: 'internal',
      skip_upload_apk: true
    )
  end

  desc "Upload AAB to internal track from path"
  lane :upload_internal do    
    upload_to_play_store(
      track: 'internal',
      skip_upload_apk: true,
      aab: 'app/build/outputs/bundle/release/app-release.aab'
    )
  end

  desc "Build AAB locally"
  lane :build_aab_local do |options|
    skip_docs
    gradle(
      task: 'bundle',
      build_type: 'release',
      release_status: 'draft',
      properties: {
        "android.injected.signing.store.file" => Dir.pwd + "/keystore.jks",
        "android.injected.signing.store.password" => options[:ANDROID_STORE_PASSWORD],
        "android.injected.signing.key.alias" => options[:ANDROID_KEY_ALIAS],
        "android.injected.signing.key.password" => options[:ANDROID_KEY_PASSWORD]
      }
    )
  end
  desc "Build apk locally"
  lane :build_apk_local do |options|

    skip_docs

    gradle(
      task: 'assemble',
      build_type: 'release',
      properties: {
        "android.injected.signing.store.file" => Dir.pwd + "/keystore.jks",
        "android.injected.signing.store.password" => options[:ANDROID_STORE_PASSWORD],
        "android.injected.signing.key.alias" => options[:ANDROID_KEY_ALIAS],
        "android.injected.signing.key.password" => options[:ANDROID_KEY_PASSWORD]
      }
    )
  end
end
